name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32wrover
          platforms: |
            - source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              name: esp32:esp32
          verbose: true
          enable-deltas-report: true
          enable-warnings-report: true
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - Software/ESP32 Sketchpad/DevKit
            - Software/ESP32 Sketchpad/Speed Test
          libraries: |
            - source-url: https://github.com/bblanchon/ArduinoJson.git
            - source-url: https://github.com/Links2004/arduinoWebSockets.git
            - source-url: https://github.com/Blueprint-Foundry/Arduino-MAX17055_Driver.git
            - source-url: https://github.com/Blueprint-Foundry/PI4IOE5V96248_Arduino_Library.git
            - source-url: https://github.com/Blueprint-Foundry/EAAPMST3923A2_Arduino_Library.git
            - source-url: https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary.git
            - source-url: https://github.com/pololu/vl53l1x-arduino.git
